(() => {
  'use strict';
  if (location.hostname !== 'chatgpt.com' || window.__NIAKGPT_V080__) return;
  window.__NIAKGPT_V080__ = true;

  const VERSION = '0.8.0';
  const CHAT_SEL = 'a[href*="/c/"]';
  const PROJECT_SEL = 'a[href^="/g/g-p-"][href$="/project"],a[href^="/g/g-p-"][href*="/project"]';
  const OWN_SEL = '#ng8-rail,#ng8-panel,#ng8-status,#ng8-coach,#ng8-pins,#ng8-quick,.ng8-bot';
  const LEGACY = new Set(['design','ai','ia','coding','code','development','web development','technology','tech','social','social media','writing','general knowledge','general','e-commerce','ecommerce','seo','marketing','business','creative','research','productivity','other','misc','work','education','health','finance','home','cars','gaming','movies','food','personal development']);
  const STOP = new Set(('le la les un une des de du et ou en sur pour avec sans dans au aux ce cet cette ces mon ma mes ton ta tes son sa ses nos vos leur leurs je tu il elle on nous vous ils elles est sont a à the and or of to for in on with from chat conversation projet project faire fais moi peux peut comment pourquoi quoi cela cette ceci avoir etre être besoin voudrais veux faudrait faut').split(/\s+/));
  const PALETTE = ['#4FC1FF','#4EC9B0','#C586C0','#DCDCAA','#CE9178','#9CDCFE','#D7BA7D','#B5CEA8','#D16969','#E06CAA','#569CD6','#6A9955','#22D3EE','#A78BFA','#FB7185','#38BDF8','#34D399','#F59E0B'];

  const state = {
    projects: [], projectById: new Map(), projectChats: new Map(), counts: new Map(), projectErrors: new Map(),
    chats: [], chatById: new Map(), profiles: new Map(), duplicateGroups: new Map(),
    health: {bridge:'ATTENTE',data:'ATTENTE',projects:'ATTENTE',organizer:'ATTENTE',pins:'ATTENTE',quick:'ATTENTE',coach:'ATTENTE',toc:'ATTENTE',performance:'ATTENTE',matrix:'ATTENTE',ui:'ATTENTE'},
    errors: [], turns: [], generation:false, wasGeneration:false, heavy:false,
    indexReady:false, indexing:false, organizerRunning:false, panelOpen:false, tab:'explorer',
    observer:null, io:null, scanTimer:0, routeTimer:0, coachTimer:0, lastPath:location.pathname,
    matrix:null, matrixRAF:0, matrixLast:0, matrixResize:null, prefetched:new Set(), dataRevision:0,
    generalEndpointOk:null, nativePinCount:0
  };

  const norm = v => String(v || '').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[’']/g,"'").replace(/\s+/g,' ').trim();
  const esc = v => String(v ?? '').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const sleep = ms => new Promise(r=>setTimeout(r,ms));
  const words = v => norm(v).replace(/[^a-z0-9à-ÿ_-]+/gi,' ').split(/\s+/).filter(x=>x.length>2&&!STOP.has(x));
  const isLegacy = p => !!p && LEGACY.has(norm(p.name));
  const activeProjects = () => state.projects.filter(p=>!isLegacy(p)&&!p.duplicateOf);

  function rememberError(scope,error){const msg=`${scope}: ${String(error?.message||error).slice(0,180)}`;state.errors.unshift(msg);state.errors=state.errors.slice(0,10);}
  function setHealth(key,value){state.health[key]=value;renderStatus();if(state.panelOpen&&state.tab==='diag')renderPanel();}
  function parseTime(v){if(typeof v==='number'&&Number.isFinite(v))return v>1e12?v:v*1000;if(typeof v==='string'){const n=Number(v);if(Number.isFinite(n))return n>1e12?n:n*1000;const d=Date.parse(v);return Number.isFinite(d)?d:0;}return 0;}
  function normalizeProjectId(v){if(!v||typeof v!=='string')return'';const s=v.trim(),m=s.match(/^g-p-([a-f0-9]+)(?:-.+)?$/i);return m?`g-p-${m[1]}`:s;}
  function projectIdFromHref(h){const m=String(h||'').match(/\/g\/(g-p-[^/]+)\/(?:project|c\/)/i);return m?normalizeProjectId(m[1]):'';}
  function chatIdFromHref(h){return String(h||'').match(/\/c\/([0-9a-f-]{20,})/i)?.[1]||'';}
  function colorFor(name){let h=0;for(const c of String(name))h=((h<<5)-h+c.charCodeAt(0))|0;return PALETTE[Math.abs(h)%PALETTE.length];}
  function iconFor(name){const s=norm(name);if(/code|dev|tech|web|api|github|program|provider/.test(s))return'</>';if(/legal|jurid|droit|prud|tribunal|justice/.test(s))return'§';if(/finance|argent|budget|banque|credit|compta/.test(s))return'€';if(/film|cinema|movie|serie|anime|video/.test(s))return'▶';if(/design|logo|image|creative|graph/.test(s))return'◇';if(/shop|commerce|store|product|produit|vente/.test(s))return'▣';if(/(^|\s)(ai|ia|gpt)(\s|$)|intelligence artificielle/.test(s))return'✦';if(/auto|car|voiture|vehicule/.test(s))return'◈';if(/health|sante|medical/.test(s))return'+';if(/game|gaming|jeu/.test(s))return'◆';if(/food|cuisine|recette/.test(s))return'◌';if(/social|relation|perso/.test(s))return'◎';return'▤';}

  let rpcSeq=0;
  function rpc(path,{method='GET',body=null,timeout=18000}={}){
    const id=`ng8-${Date.now()}-${++rpcSeq}`;
    return new Promise(resolve=>{
      const timer=setTimeout(()=>{cleanup();resolve({ok:false,status:0,error:'rpc_timeout'});},timeout);
      const handler=e=>{if(e.detail?.id!==id)return;cleanup();resolve(e.detail);};
      const cleanup=()=>{clearTimeout(timer);document.removeEventListener('niakgpt:rpc-response',handler);};
      document.addEventListener('niakgpt:rpc-response',handler);
      document.dispatchEvent(new CustomEvent('niakgpt:rpc-request',{detail:{id,path,method,body}}));
    });
  }

  function projectFromRaw(raw){
    const gizmo=raw?.gizmo?.gizmo||raw?.gizmo||raw;const id=normalizeProjectId(gizmo?.id||raw?.id||'');const name=String(gizmo?.display?.name||gizmo?.name||raw?.display?.name||'').trim();
    if(!id.startsWith('g-p-')||!name)return null;
    return {id,name,description:String(gizmo?.display?.description||gizmo?.description||''),instructions:String(gizmo?.instructions||''),color:colorFor(name),icon:iconFor(name),href:`/g/${id}/project`,duplicateOf:''};
  }
  function normalizeChat(raw,forcedProject=''){const id=String(raw?.id||raw?.conversation_id||'');if(!id)return null;return{id,title:String(raw?.title||raw?.conversation_title||'Conversation sans titre'),projectId:normalizeProjectId(forcedProject||raw?.gizmo_id||raw?.conversation_mode?.gizmo_id||''),snippet:String(raw?.snippet||''),updated:parseTime(raw?.update_time||raw?.create_time),href:''};}
  function upsertProject(p){if(!p?.id)return;const old=state.projectById.get(p.id),merged={...old,...p,color:p.color||old?.color||colorFor(p.name),icon:p.icon||old?.icon||iconFor(p.name)};state.projectById.set(p.id,merged);if(!old)state.projects.push(merged);else{const i=state.projects.findIndex(x=>x.id===p.id);if(i>=0)state.projects[i]=merged;}}
  function upsertChat(c){if(!c?.id)return;const old=state.chatById.get(c.id),merged={...old,...c,projectId:c.projectId||old?.projectId||'',updated:Math.max(old?.updated||0,c.updated||0),href:c.href||old?.href||''};state.chatById.set(c.id,merged);if(!old)state.chats.push(merged);else{const i=state.chats.findIndex(x=>x.id===c.id);if(i>=0)state.chats[i]=merged;}}

  async function fetchAllProjects(){const found=new Map(),seen=new Set();let cursor=null;for(let page=0;page<80;page++){const qs=new URLSearchParams({conversations_per_gizmo:'0'});if(cursor!=null)qs.set('cursor',String(cursor));const r=await rpc(`/backend-api/gizmos/snorlax/sidebar?${qs}`);if(!r.ok){if(page===0)throw new Error(`Projects ${r.status||0} · ${r.error||'error'}`);rememberError('projects-page',r.error||r.status);break;}for(const raw of Array.isArray(r.data?.items)?r.data.items:[]){const p=projectFromRaw(raw);if(p)found.set(p.id,p);}const next=r.data?.cursor??null;if(next==null)break;const key=String(next);if(seen.has(key))break;seen.add(key);cursor=next;}return[...found.values()];}
  async function fetchProjectChats(project){const out=new Map(),seen=new Set();let cursor=0;for(let page=0;page<250;page++){const qs=new URLSearchParams({cursor:String(cursor),limit:'100'});const r=await rpc(`/backend-api/gizmos/${encodeURIComponent(project.id)}/conversations?${qs}`,{timeout:18000});if(!r.ok)throw new Error(`${r.status||0} · ${r.error||'error'}`);const items=Array.isArray(r.data?.items)?r.data.items:[];for(const raw of items){const c=normalizeChat(raw,project.id);if(c)out.set(c.id,c);}const next=r.data?.cursor??null;if(!items.length||next==null)break;const key=String(next);if(seen.has(key))break;seen.add(key);cursor=next;}return[...out.values()];}
  async function fetchGeneralChatsBestEffort(){
    const out=new Map();let offset=0;const limit=100;
    for(let page=0;page<120;page++){
      const qs=new URLSearchParams({offset:String(offset),limit:String(limit),order:'updated'});
      let r=await rpc(`/backend-api/conversations?${qs}`,{timeout:18000});
      if(!r.ok){
        if(page===0){state.generalEndpointOk=false;rememberError('general-conversations',`${r.status||0} · ${r.error||'error'} · ${r.transport||''}`);}else rememberError('general-conversations-page',r.error||r.status);
        break;
      }
      state.generalEndpointOk=true;
      const items=Array.isArray(r.data?.items)?r.data.items:[];for(const raw of items){const c=normalizeChat(raw);if(c)out.set(c.id,c);}if(!items.length)break;offset+=items.length;const more=r.data?.has_more===true||r.data?.hasMore===true;if(!more&&items.length<limit)break;
    }
    return[...out.values()];
  }
  async function pool(items,limit,worker){let i=0;async function run(){while(i<items.length){const n=i++;await worker(items[n],n);}}await Promise.all(Array.from({length:Math.min(limit,items.length)},run));}

  function navRoot(){return document.querySelector('[data-testid="conversation-sidebar"]')||document.querySelector('[data-testid="sidebar"]')||[...document.querySelectorAll('nav,aside')].find(x=>x.querySelector(CHAT_SEL)||x.querySelector(PROJECT_SEL))||document.querySelector('nav')||null;}
  function mergeDOM(){const root=navRoot()||document;for(const a of root.querySelectorAll(PROJECT_SEL)){if(!(a instanceof HTMLAnchorElement)||a.closest(OWN_SEL))continue;const id=projectIdFromHref(a.getAttribute('href')),name=(a.getAttribute('aria-label')||a.querySelector('.truncate span')?.textContent||a.textContent||'').trim();if(id&&name)upsertProject({id,name,color:colorFor(name),icon:iconFor(name),href:a.getAttribute('href')||`/g/${id}/project`,duplicateOf:''});}for(const a of root.querySelectorAll(CHAT_SEL)){if(!(a instanceof HTMLAnchorElement)||a.closest(OWN_SEL))continue;const id=chatIdFromHref(a.getAttribute('href'));if(!id)continue;const title=(a.getAttribute('aria-label')||a.querySelector('.truncate span')?.textContent||a.textContent||id).trim();upsertChat({id,title,projectId:projectIdFromHref(a.getAttribute('href')),snippet:'',updated:0,href:a.getAttribute('href')||''});}}

  function buildDuplicates(){state.duplicateGroups.clear();for(const p of state.projects){const k=norm(p.name);if(!state.duplicateGroups.has(k))state.duplicateGroups.set(k,[]);state.duplicateGroups.get(k).push(p);}for(const group of state.duplicateGroups.values()){if(group.length<2)continue;group.sort((a,b)=>(state.counts.get(b.id)||0)-(state.counts.get(a.id)||0)||projectRecency(b.id)-projectRecency(a.id)||a.id.localeCompare(b.id));const canonical=group[0];for(const p of group)p.duplicateOf=p.id===canonical.id?'':canonical.id;}}
  function projectRecency(id){let t=0;for(const c of state.chats)if(c.projectId===id)t=Math.max(t,c.updated||0);return t;}
  function buildProfiles(){const profiles=new Map();for(const p of state.projects){const f=new Map(),add=(txt,w)=>{for(const t of words(txt))f.set(t,(f.get(t)||0)+w);};add(p.name,34);add(p.description,12);add(p.instructions,9);profiles.set(p.id,f);}for(const c of state.chats){const f=profiles.get(c.projectId);if(!f)continue;for(const t of words(`${c.title} ${c.snippet}`))f.set(t,(f.get(t)||0)+3);}state.profiles=profiles;}

  async function indexEverything({quiet=false}={}){
    if(state.indexing||state.generation)return false;state.indexing=true;state.indexReady=false;state.dataRevision++;
    try{
      setHealth('data','INDEXATION · Projects');
      const projects=await fetchAllProjects();state.projects=[];state.projectById.clear();for(const p of projects)upsertProject(p);mergeDOM();setHealth('bridge','OK');setHealth('projects',`OK · ${state.projects.length}/${state.projects.length}`);renderPins();

      state.projectChats.clear();state.counts.clear();state.projectErrors.clear();state.chats=[];state.chatById.clear();let done=0;
      setHealth('data',`INDEXATION · chats Projects 0/${state.projects.length}`);
      await pool(state.projects,4,async p=>{
        try{const list=await fetchProjectChats(p),map=new Map();for(const c of list){map.set(c.id,c);upsertChat(c);}state.projectChats.set(p.id,map);state.counts.set(p.id,map.size);}catch(error){state.projectErrors.set(p.id,String(error?.message||error));state.counts.set(p.id,null);rememberError(`project:${p.name}`,error);}done++;if(done%2===0||done===state.projects.length){setHealth('data',`INDEXATION · chats Projects ${done}/${state.projects.length}`);renderPins();if(state.panelOpen)renderPanel();}});

      setHealth('data','INDEXATION · hors Project');
      const general=await fetchGeneralChatsBestEffort();for(const c of general)upsertChat(c);mergeDOM();
      buildDuplicates();buildProfiles();state.indexReady=true;
      const exact=state.projects.filter(p=>state.counts.get(p.id)!=null).length;
      setHealth('projects',`OK · ${state.projects.length}/${state.projects.length} · ${exact} comptés`);
      setHealth('data',`OK · ${state.projects.length} Projects · ${state.chats.length} chats${state.generalEndpointOk===false?' · global indisponible':''}`);
      setHealth('quick',`OK · ${state.projects.length+state.chats.length} entrées`);
      if(!quiet){renderPins();decorateSidebar();renderPanel();renderStatus();applyProjectTheme();}
      return true;
    }catch(error){rememberError('index',error);setHealth('data',`ERREUR · ${String(error?.message||error).slice(0,100)}`);return false;}finally{state.indexing=false;}
  }

  function escapeRx(s){return String(s).replace(/[.*+?^${}()|[\]\\]/g,'\\$&');}
  function scoreText(text,p){const s=norm(text),pn=norm(p.name);let score=0;if(pn.length>=3&&s.includes(pn))score+=260;for(const t of words(p.name))if(new RegExp(`\\b${escapeRx(t)}\\b`,'i').test(s))score+=42;const f=state.profiles.get(p.id)||new Map();for(const t of new Set(words(text)))score+=Math.min(22,f.get(t)||0);return score;}
  function bestTarget(chat,extra=''){const ranked=activeProjects().map(p=>({project:p,score:scoreText(`${chat.title} ${chat.snippet} ${extra}`,p)})).sort((a,b)=>b.score-a.score);const first=ranked[0],second=ranked[1];return first?{...first,margin:first.score-(second?.score||0)}:null;}
  function conversationText(data){const out=[];for(const node of Object.values(data?.mapping||{})){const m=node?.message;if(!m||!['user','assistant'].includes(m?.author?.role))continue;for(const p of Array.isArray(m?.content?.parts)?m.content.parts:[])if(typeof p==='string')out.push(p);if(out.join(' ').length>12000)break;}return out.join(' ').slice(0,12000);}
  async function verifyProject(chatId){const r=await rpc(`/backend-api/conversation/${encodeURIComponent(chatId)}`,{timeout:12000});return r.ok?normalizeProjectId(r.data?.gizmo_id||r.data?.conversation_mode?.gizmo_id||''):'';}
  async function moveChat(chat,target){const path=`/backend-api/conversation/${encodeURIComponent(chat.id)}`;await rpc(path,{method:'PATCH',body:{gizmo_id:target.id},timeout:12000});const got=await verifyProject(chat.id);if(got!==target.id)return false;const old=chat.projectId;chat.projectId=target.id;if(old&&state.counts.get(old)!=null)state.counts.set(old,Math.max(0,(state.counts.get(old)||0)-1));if(state.counts.get(target.id)!=null)state.counts.set(target.id,(state.counts.get(target.id)||0)+1);state.projectChats.get(old)?.delete(chat.id);if(!state.projectChats.has(target.id))state.projectChats.set(target.id,new Map());state.projectChats.get(target.id).set(chat.id,chat);return true;}

  async function consolidateDuplicates(){let moved=0,ambiguous=0;for(const group of state.duplicateGroups.values()){if(group.length<2)continue;const canonical=group.find(p=>!p.duplicateOf)||group[0];for(const dup of group.filter(p=>p.id!==canonical.id)){const chats=[...(state.projectChats.get(dup.id)?.values()||[])];for(const chat of chats){if(state.generation)return{moved,ambiguous};if(await moveChat(chat,canonical))moved++;else ambiguous++;}}}buildDuplicates();return{moved,ambiguous};}
  async function repairOrganization({manual=false}={}){
    if(state.organizerRunning||!state.indexReady||state.generation)return;state.organizerRunning=true;let moved=0,ambiguous=0,failed=0,deep=0,duplicatesMoved=0;
    try{
      const dup=await consolidateDuplicates();duplicatesMoved=dup.moved;
      const candidates=state.chats.filter(c=>!c.projectId||isLegacy(state.projectById.get(c.projectId))||state.projectById.get(c.projectId)?.duplicateOf).sort((a,b)=>b.updated-a.updated);
      const batch=manual?candidates:candidates.slice(0,100);setHealth('organizer',`EN COURS · 0/${batch.length}`);
      for(let i=0;i<batch.length;i++){
        if(state.generation)break;const chat=batch[i],source=state.projectById.get(chat.projectId);if(source?.duplicateOf)continue;const fromLegacy=isLegacy(source);let best=bestTarget(chat),threshold=fromLegacy?52:38,margin=fromLegacy?16:12;
        if(!best||best.score<threshold||best.margin<margin){if(deep<(manual?160:50)){const d=await rpc(`/backend-api/conversation/${encodeURIComponent(chat.id)}`,{timeout:10000});deep++;if(d.ok){best=bestTarget(chat,conversationText(d.data));threshold=fromLegacy?72:58;margin=fromLegacy?18:15;}}}
        if(!best||best.score<threshold||best.margin<margin)ambiguous++;else if(await moveChat(chat,best.project))moved++;else failed++;
        if(i%5===0||i===batch.length-1){setHealth('organizer',`EN COURS · ${i+1}/${batch.length} · ${moved+duplicatesMoved} déplacés`);await sleep(0);}
      }
      buildProfiles();buildDuplicates();setHealth('organizer',`OK · ${moved+duplicatesMoved} déplacés · ${ambiguous} ambigus${failed?` · ${failed} échecs`:''}`);renderPins();decorateSidebar();renderPanel();
    }catch(error){rememberError('organizer',error);setHealth('organizer',`ERREUR · ${String(error?.message||error).slice(0,90)}`);}finally{state.organizerRunning=false;}
  }

  function currentChatId(){return chatIdFromHref(location.pathname);}
  function currentProject(){const pid=projectIdFromHref(location.pathname),direct=state.projectById.get(pid);if(direct)return direct;const c=state.chatById.get(currentChatId());return c?state.projectById.get(c.projectId)||null:null;}
  function applyProjectTheme(){const p=currentProject();document.documentElement.style.setProperty('--ng8-current-project',p?.color||'#3794ff');document.documentElement.dataset.ng8Project=p?.id||'';}

  function textIs(el,rx){return rx.test((el.textContent||'').trim());}
  function heading(root,rx){return [...root.querySelectorAll('div,span,h2,h3,p')].find(el=>textIs(el,rx));}
  function nativePinnedProjectIds(){const root=navRoot();if(!root)return new Set();const pinHead=heading(root,/^(épinglés|epingles|pinned)$/i),recentHead=heading(root,/^(récents|recents|recent)$/i);if(!pinHead)return new Set();const top=pinHead.getBoundingClientRect().bottom,bottom=recentHead?.getBoundingClientRect().top??Infinity,ids=new Set();for(const a of root.querySelectorAll(PROJECT_SEL)){if(a.closest('#ng8-pins'))continue;const r=a.getBoundingClientRect();if(r.top>=top-2&&r.bottom<=bottom+2){const id=projectIdFromHref(a.getAttribute('href'));if(id)ids.add(id);}}return ids;}
  function sortedProjects(){return [...state.projects].sort((a,b)=>{const ad=!!a.duplicateOf,bd=!!b.duplicateOf;if(ad!==bd)return ad?1:-1;const al=isLegacy(a),bl=isLegacy(b);if(al!==bl)return al?1:-1;const ac=state.counts.get(a.id),bc=state.counts.get(b.id);if((ac>0)!==(bc>0))return ac>0?-1:1;return projectRecency(b.id)-projectRecency(a.id)||a.name.localeCompare(b.name,'fr');});}
  function renderPins(){const root=navRoot();if(!root||!state.projects.length)return;document.getElementById('ng8-pins')?.remove();const box=document.createElement('section');box.id='ng8-pins';const projects=sortedProjects();box.innerHTML=`<div class="ng8-pin-head"><span>PROJECTS ÉPINGLÉS</span><b>${projects.length}</b></div><div class="ng8-pin-list">${projects.map(p=>`<a href="${esc(p.href)}" data-ng8-pin="1" data-legacy="${isLegacy(p)?'1':'0'}" data-duplicate="${p.duplicateOf?'1':'0'}" style="--ng-project:${p.color}" title="${esc(p.name)}"><i>${esc(p.icon)}</i><span>${esc(p.name)}</span><small>${state.counts.has(p.id)?(state.counts.get(p.id)==null?'?':state.counts.get(p.id)):'…'}</small></a>`).join('')}</div>`;
    const pinHead=heading(root,/^(épinglés|epingles|pinned)$/i),recent=heading(root,/^(récents|recents|recent)$/i),projectsBtn=[...root.querySelectorAll('a,button')].find(x=>/^(projets|projects)$/i.test((x.textContent||'').trim()));
    if(pinHead?.parentElement)pinHead.parentElement.insertAdjacentElement('afterend',box);else if(recent?.parentElement)recent.parentElement.insertAdjacentElement('beforebegin',box);else if(projectsBtn?.parentElement)projectsBtn.parentElement.insertAdjacentElement('afterend',box);else root.prepend(box);
    const native=nativePinnedProjectIds();state.nativePinCount=native.size;setHealth('pins',`OK · ${projects.length}/${projects.length} visibles · ${native.size}/${projects.length} natifs`);
  }
  function decorateSidebar(){const root=navRoot();if(!root)return;root.classList.add('ng8-sidebar');let zi=0;for(const a of [...root.querySelectorAll(CHAT_SEL)].filter(x=>!x.closest(OWN_SEL))){const id=chatIdFromHref(a.getAttribute('href'));if(!id)continue;const chat=state.chatById.get(id),p=chat?state.projectById.get(chat.projectId):null;a.dataset.ng8Chat='1';a.dataset.ng8Zebra=String(zi++%2);a.style.setProperty('--ng-project',p?.color||'#607080');a.classList.toggle('ng8-current',id===currentChatId());let badge=a.querySelector(':scope > .ng8-chat-project');if(p&&!badge){badge=document.createElement('span');badge.className='ng8-chat-project';a.appendChild(badge);}if(badge){badge.textContent=p?.name||'';badge.style.setProperty('--ng-project',p?.color||'#607080');badge.hidden=!p;}}
    for(const a of [...root.querySelectorAll(PROJECT_SEL)].filter(x=>!x.closest(OWN_SEL))){const id=projectIdFromHref(a.getAttribute('href')),p=state.projectById.get(id);if(!p)continue;a.dataset.ng8Project='1';a.dataset.ng8Icon=p.icon;a.style.setProperty('--ng-project',p.color);a.classList.toggle('ng8-legacy',isLegacy(p));a.classList.toggle('ng8-duplicate',!!p.duplicateOf);a.classList.toggle('ng8-empty',state.counts.get(id)===0);}
  }
  async function tryNativePins(){const root=navRoot();if(!root)return;let native=nativePinnedProjectIds(),attempted=0,clicked=0;for(const p of sortedProjects()){if(native.has(p.id)||p.duplicateOf)continue;const a=[...root.querySelectorAll(PROJECT_SEL)].filter(x=>!x.closest('#ng8-pins')).find(x=>projectIdFromHref(x.getAttribute('href'))===p.id);if(!a)continue;const row=a.closest('li')||a.parentElement;a.dispatchEvent(new MouseEvent('mouseenter',{bubbles:true}));row?.dispatchEvent(new MouseEvent('mouseenter',{bubbles:true}));await sleep(80);const buttons=[...(row?.querySelectorAll('button')||[])],menu=buttons.find(b=>/more|options|menu|davantage|plus/i.test(`${b.getAttribute('aria-label')||''} ${b.title||''}`))||buttons.at(-1);if(!menu)continue;attempted++;menu.click();await sleep(120);const item=[...document.querySelectorAll('[role="menuitem"],[role="menuitemradio"],[role="option"]')].find(x=>/^(épingler|epingler|pin)\b/i.test((x.textContent||'').trim()));if(item){item.click();clicked++;await sleep(150);}else document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));native=nativePinnedProjectIds();}state.nativePinCount=native.size;setHealth('pins',`OK · ${state.projects.length}/${state.projects.length} visibles · ${native.size}/${state.projects.length} natifs${attempted?` · ${clicked}/${attempted} actions`:''}`);renderPins();}

  function getTurns(){const set=new Set();document.querySelectorAll('article[data-testid^="conversation-turn-"],[data-testid^="conversation-turn-"]').forEach(x=>set.add(x));return[...set].filter(x=>x instanceof HTMLElement&&x.textContent?.trim());}
  function roleOf(t){return t.querySelector('[data-message-author-role]')?.getAttribute('data-message-author-role')||'';}
  function ensureIO(){if(state.io)return;state.io=new IntersectionObserver(entries=>{for(const e of entries)e.target.classList.toggle('ng8-offscreen',!e.isIntersecting);},{rootMargin:'1200px 0px'});}
  function enhanceCode(root){root.querySelectorAll('pre').forEach(pre=>{if(pre.dataset.ng8Code)return;pre.dataset.ng8Code='1';const code=pre.querySelector('code'),lang=(code?.className?.match(/language-([\w+-]+)/)?.[1]||'code').toUpperCase(),lines=(code?.innerText||pre.innerText||'').split('\n').length,bar=document.createElement('div');bar.className='ng8-codebar';bar.innerHTML=`<span><i>●</i> ${esc(lang)} · ${lines} lignes</span><button type="button">COPIER</button>`;bar.querySelector('button').onclick=()=>navigator.clipboard.writeText(code?.innerText||pre.innerText||'');pre.prepend(bar);});}
  function decorateTurns(light=false){const turns=getTurns();state.turns=turns;state.heavy=turns.length>=70||document.querySelectorAll('pre,table,.katex-display,mjx-container').length>=40;document.documentElement.dataset.ng8Heavy=state.heavy?'1':'0';ensureIO();const start=light?Math.max(0,turns.length-4):0;for(let i=start;i<turns.length;i++){const t=turns[i];t.dataset.ng8Turn=String(i);t.dataset.ng8Role=roleOf(t)||'unknown';t.dataset.ng8Zebra=String(i%2);enhanceCode(t);if(i<turns.length-10&&!t.dataset.ng8Observed){t.dataset.ng8Observed='1';state.io.observe(t);}}setHealth('toc',turns.length?`OK · ${turns.length}`:'ATTENTE');setHealth('performance',`OK · ${turns.length}${state.heavy?' · LOURD':''}`);}

  function findComposer(){const editors=[...document.querySelectorAll('#prompt-textarea,[data-testid="prompt-textarea"],textarea,[contenteditable="true"]')].filter(el=>{const r=el.getBoundingClientRect();return r.width>240&&r.height>18&&r.bottom>innerHeight*.45;});const editor=editors.sort((a,b)=>b.getBoundingClientRect().top-a.getBoundingClientRect().top)[0];if(!editor)return null;const form=editor.closest('form')||editor.closest('[data-type="unified-composer"]')||editor.closest('[class*="composer"]')||editor.parentElement;return{editor,form,shell:form?.parentElement||form};}
  function editorText(e){return e instanceof HTMLTextAreaElement?e.value:(e.innerText||e.textContent||'');}
  function recentContext(){return state.turns.slice(-5).map(t=>t.innerText||t.textContent||'').join(' ').slice(-6500);}
  function subject(prompt){const clean=String(prompt||'').replace(/\s+/g,' ').trim();if(!clean)return'ce point';const p=clean.split(/[.!?;\n]+/).map(x=>x.trim()).filter(Boolean).at(-1)||clean;return p.length>85?p.slice(0,82)+'…':p;}
  function suggestions(prompt){const ctx=norm(`${prompt} ${recentContext()}`),s=subject(prompt),p=currentProject(),scope=p?` dans « ${p.name} »`:'';const out=[],add=(kind,title,text)=>{if(!out.some(x=>x.text===text))out.push({kind,title,text});};if(/bug|erreur|marche pas|fonctionne pas|chevauch|overlap|dom|extension|javascript|css|code/.test(ctx)){add('code','Cause racine',`Pour « ${s} », identifie la cause racine${scope} avant toute modification.`);add('test','Runtime',`Teste « ${s} » avec navigation SPA, gros fil, redimensionnement et pièces jointes.`);add('perf','Régression',`Vérifie que « ${s} » n’ajoute ni boucle DOM, ni reflow coûteux, ni double injection.`);}if(/image|photo|fichier|piece jointe|upload|attachment/.test(ctx))add('ux','Pièces jointes',`Pour « ${s} », garde previews, saisie et recommandations dans un flux sans chevauchement.`);if(/design|da|couleur|fond|interface|ux|ui|styl|icone/.test(ctx)){add('design','DA système',`Pour « ${s} », harmonise couleurs, fonds, icônes, états et contrastes comme un seul système.`);add('ux','Lisibilité',`Sur « ${s} », privilégie densité, scan et contraste avant la décoration.`);}if(/projet|project|class|rang|dossier|organis|epingle|pin/.test(ctx)){add('organize','Organisation',`Pour « ${s} », protège les vrais Projects, répare les génériques et vérifie chaque déplacement.`);add('table','Audit',`Pour « ${s} », vérifie les compteurs et éléments réellement indexés.`);}if(/cherche|verifie|actuel|recent|prix|tarif|loi|regle|source/.test(ctx))add('research','Sources',`Pour « ${s} », vérifie les informations actuelles avec des sources primaires.`);if(/compar| vs |versus/.test(` ${ctx} `))add('table','Comparaison',`Compare « ${s} » dans un tableau dense avec critères, avantages, limites et décision.`);if(!out.length&&prompt.trim().length>3){add('focus','Objectif',`Traite précisément « ${s} »${scope} et élimine le hors-sujet.`);add('blind','Angles morts',`Sur « ${s} », signale les hypothèses capables de changer le résultat.`);add('action','Action',`Termine « ${s} » par la prochaine action concrète la plus utile.`);}return out.slice(0,4);}
  function appendPrompt(editor,text){editor.focus();if(editor instanceof HTMLTextAreaElement){const sep=editor.value.trim()?'\n\n':'',s=editor.selectionStart??editor.value.length,e=editor.selectionEnd??editor.value.length;editor.setRangeText(`${sep}${text}`,s,e,'end');editor.dispatchEvent(new Event('input',{bubbles:true}));return;}const sel=getSelection(),r=document.createRange();r.selectNodeContents(editor);r.collapse(false);sel.removeAllRanges();sel.addRange(r);document.execCommand('insertText',false,`${editorText(editor).trim()?'\n\n':''}${text}`);editor.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText'}));}
  function ensureCoach(){if(state.generation){document.getElementById('ng8-coach')?.setAttribute('hidden','');return;}const c=findComposer();if(!c?.editor||!c.form||!c.shell){setHealth('coach','ATTENTE');return;}let box=document.getElementById('ng8-coach');if(box&&box.parentElement!==c.shell){box.remove();box=null;}if(!box){box=document.createElement('div');box.id='ng8-coach';c.shell.insertBefore(box,c.form);}const prompt=editorText(c.editor),items=suggestions(prompt),attachments=c.form.querySelectorAll('img,[data-testid*="attachment"],[class*="attachment"],[data-testid*="file"],[class*="file"]:not(input)').length;box.classList.toggle('compact',attachments>0||c.form.getBoundingClientRect().height>180);box.hidden=prompt.trim().length<4||!items.length;box.innerHTML=`<div class="ng8-coach-label">✦ NIAKGPT · RECO${attachments?` · ${attachments} PJ`:''}</div><div class="ng8-sug-grid">${items.map((x,i)=>`<button type="button" data-i="${i}" class="ng8-sug ng8-${x.kind}"><b>${esc(x.title)}</b><span>${esc(x.text)}</span></button>`).join('')}</div>`;box.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>appendPrompt(c.editor,items[Number(b.dataset.i)].text));setHealth('coach','OK');}

  function ensureMatrix(){if(matchMedia('(prefers-reduced-motion: reduce)').matches){setHealth('matrix','OFF');return;}const host=document.querySelector('main')||document.body;if(!host)return;if(state.matrix?.isConnected&&state.matrix.parentElement===host)return;state.matrix?.remove();if(state.matrixRAF)cancelAnimationFrame(state.matrixRAF);const canvas=document.createElement('canvas');canvas.id='ng8-matrix';host.prepend(canvas);state.matrix=canvas;const ctx=canvas.getContext('2d',{alpha:true});let cols=[],w=0,h=0;const resize=()=>{const r=host.getBoundingClientRect(),scale=.52;w=canvas.width=Math.max(1,Math.floor(r.width*scale));h=canvas.height=Math.max(1,Math.floor(innerHeight*scale));canvas.style.width=`${Math.max(1,r.width)}px`;canvas.style.height=`${innerHeight}px`;cols=Array(Math.ceil(w/10)).fill(0).map(()=>Math.random()*h);};resize();state.matrixResize=resize;const chars='01アイウエオカキクケコｱｲｳｴｵ<>[]{}▓░λΣ∞';const draw=t=>{state.matrixRAF=requestAnimationFrame(draw);const gap=state.generation?(state.heavy?260:140):60;if(document.hidden||t-state.matrixLast<gap)return;state.matrixLast=t;ctx.fillStyle='rgba(2,8,5,.12)';ctx.fillRect(0,0,w,h);ctx.font='10px ui-monospace,Consolas,monospace';for(let i=0;i<cols.length;i++){ctx.fillStyle=Math.random()>.975?'rgba(210,255,220,.93)':'rgba(30,255,92,.62)';ctx.fillText(chars[(Math.random()*chars.length)|0],i*10,cols[i]);cols[i]+=8.5;if(cols[i]>h&&Math.random()>.965)cols[i]=0;}};state.matrixRAF=requestAnimationFrame(draw);setHealth('matrix','OK');}
  function botSVG(){return`<svg viewBox="0 0 64 64"><path d="M18 10h28l8 11-3 25-9 8H22l-9-8-3-25z" fill="#8b949e" stroke="#d0d7de" stroke-width="2"/><path d="M18 19h28l4 7-5 10H19l-5-10z" fill="#151b22"/><circle cx="24" cy="28" r="4" fill="#ff3b30"/><circle cx="40" cy="28" r="4" fill="#ff3b30"/><path d="M24 41h16v10H24z" fill="#343b43"/></svg>`;}
  function ensureBots(){if(!document.body||document.getElementById('ng8-bot-a'))return;for(const [id,title]of[['ng8-bot-a',"I'll be back."],['ng8-bot-b','Skynet online.'],['ng8-bot-c','T-800-ish.']]){const d=document.createElement('div');d.id=id;d.className='ng8-bot';d.innerHTML=botSVG();d.title=title;document.body.appendChild(d);}}
  function brand(){if(document.title.includes('ChatGPT'))document.title=document.title.replace(/ChatGPT/g,'NiakGPT');for(const el of document.querySelectorAll('header a,header button,header span,nav a,nav button,nav span')){const r=el.getBoundingClientRect(),txt=(el.textContent||'').trim();if(r.top<90&&r.left<350&&txt==='ChatGPT'){const walker=document.createTreeWalker(el,NodeFilter.SHOW_TEXT);let n;while((n=walker.nextNode()))if(n.nodeValue?.trim()==='ChatGPT'){n.nodeValue='NiakGPT';el.dataset.ng8Brand='1';return;}}}}

  function generating(){return[...document.querySelectorAll('button,[data-testid]')].filter(el=>el.getBoundingClientRect().width>0).some(el=>/stop|arrêter|arreter/i.test(`${el.getAttribute('aria-label')||''} ${el.getAttribute('data-testid')||''}`));}
  function markRunning(){state.wasGeneration=state.generation;state.generation=generating();document.documentElement.dataset.ng8Running=state.generation?'1':'0';const p=currentProject(),cid=currentChatId();document.querySelectorAll('[data-ng8-pin],[data-ng8-project]').forEach(x=>x.classList.toggle('ng8-running',!!state.generation&&!!p&&(x.getAttribute('href')||'').includes(p.id)));document.querySelectorAll('[data-ng8-chat]').forEach(x=>x.classList.toggle('ng8-running',!!state.generation&&!!cid&&(x.getAttribute('href')||'').includes(cid)));if(state.wasGeneration&&!state.generation)setTimeout(async()=>{await indexEverything({quiet:true});await repairOrganization({manual:false});renderPins();decorateSidebar();},1200);renderStatus();}

  function ensureShell(){if(!document.body||document.getElementById('ng8-rail'))return;const rail=document.createElement('aside');rail.id='ng8-rail';rail.innerHTML=`<button data-tab="explorer" title="Explorer">▤</button><button data-tab="toc" title="Sommaire">☷</button><button data-tab="diag" title="Diagnostic">◉</button><span></span><button data-quick title="Quick Open · Alt+K">⌘</button>`;document.body.appendChild(rail);const panel=document.createElement('aside');panel.id='ng8-panel';document.body.appendChild(panel);const status=document.createElement('div');status.id='ng8-status';document.body.appendChild(status);document.body.classList.add('ng8-ready');rail.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{const tab=b.dataset.tab;state.panelOpen=!(state.panelOpen&&state.tab===tab);state.tab=tab;renderPanel();});rail.querySelector('[data-quick]').onclick=openQuick;setHealth('ui','OK');}
  function renderStatus(){const s=document.getElementById('ng8-status');if(!s)return;const p=currentProject(),err=Object.values(state.health).some(v=>String(v).startsWith('ERREUR'));s.classList.toggle('running',state.generation);s.innerHTML=`<span><b>NiakGPT</b> ${VERSION}</span><span>${esc(p?.name||'Hors projet')}</span><button data-q>⌘ Alt+K</button><strong>BY SKYNET</strong><span>${state.generation?'EXÉCUTION':err?'DIAGNOSTIC':'PRÊT'}</span>`;s.querySelector('[data-q]').onclick=openQuick;applyProjectTheme();}
  function renderPanel(){const p=document.getElementById('ng8-panel');if(!p)return;p.classList.toggle('open',state.panelOpen);document.body.classList.toggle('ng8-panel-open',state.panelOpen);document.querySelectorAll('#ng8-rail [data-tab]').forEach(b=>b.classList.toggle('active',state.panelOpen&&b.dataset.tab===state.tab));if(!state.panelOpen)return;if(state.tab==='diag'){p.innerHTML=`<header><div><small>DIAGNOSTIC</small><b>État réel des modules</b></div><button>×</button></header><div class="ng8-diag">${Object.entries(state.health).map(([k,v])=>`<div><span>${esc(k)}</span><b class="${String(v).startsWith('OK')?'ok':String(v).startsWith('ERREUR')?'err':'wait'}">${esc(v)}</b></div>`).join('')}</div>${state.errors.length?`<details class="ng8-errors"><summary>Dernières erreurs</summary>${state.errors.map(e=>`<code>${esc(e)}</code>`).join('')}</details>`:''}<div class="ng8-joke">☠ SYSTEM // SKYNET</div>`;}else if(state.tab==='toc'){p.innerHTML=`<header><div><small>SOMMAIRE</small><b>${state.turns.length} blocs</b></div><button>×</button></header><input id="ng8-toc-search" placeholder="Filtrer le fil…"><div class="ng8-toc">${state.turns.map((t,i)=>`<button data-turn="${i}"><i>${String(i+1).padStart(2,'0')}</i><span>${esc((t.innerText||t.textContent||'').replace(/\s+/g,' ').slice(0,130))}</span></button>`).join('')}</div>`;}else{const projects=sortedProjects();p.innerHTML=`<header><div><small>EXPLORER</small><b>${state.projects.length} Projects · ${state.chats.length} chats</b></div><button>×</button></header><div class="ng8-actions"><button data-repair>Réparer le classement</button><button data-refresh>Réindexer</button></div><input id="ng8-project-search" placeholder="Filtrer les Projects…"><div class="ng8-project-table"><div class="head"><span>Projet</span><span>Chats</span></div>${projects.map(x=>`<a href="${esc(x.href)}" data-project-name="${esc(norm(x.name))}" style="--ng-project:${x.color}" class="${isLegacy(x)?'legacy ':''}${x.duplicateOf?'duplicate':''}"><i>${esc(x.icon)}</i><span>${esc(x.name)}${x.duplicateOf?' · doublon':''}</span><b>${state.counts.has(x.id)?(state.counts.get(x.id)==null?'?':state.counts.get(x.id)):'…'}</b></a>`).join('')}</div>`;}
    p.querySelector('header button')?.addEventListener('click',()=>{state.panelOpen=false;renderPanel();});p.querySelector('[data-repair]')?.addEventListener('click',()=>repairOrganization({manual:true}));p.querySelector('[data-refresh]')?.addEventListener('click',async()=>{await indexEverything();await repairOrganization({manual:false});tryNativePins();renderPanel();});p.querySelectorAll('[data-turn]').forEach(b=>b.onclick=()=>state.turns[Number(b.dataset.turn)]?.scrollIntoView({behavior:'smooth',block:'center'}));const ts=p.querySelector('#ng8-toc-search');if(ts)ts.oninput=()=>{const q=norm(ts.value);p.querySelectorAll('[data-turn]').forEach(b=>b.hidden=!!q&&!norm(b.textContent).includes(q));};const ps=p.querySelector('#ng8-project-search');if(ps)ps.oninput=()=>{const q=norm(ps.value);p.querySelectorAll('.ng8-project-table a').forEach(a=>a.hidden=!!q&&!String(a.dataset.projectName||'').includes(q));};}

  function chatHref(c){return c.href||(c.projectId?`/g/${c.projectId}/c/${c.id}`:`/c/${c.id}`);}
  function routeTo(href){if(!href)return;const a=[...document.querySelectorAll('a')].find(x=>x.getAttribute('href')===href&&!x.closest(OWN_SEL));if(a){a.click();return;}location.href=href;}
  async function prefetch(c){if(!c?.id||state.prefetched.has(c.id))return;state.prefetched.add(c.id);await rpc(`/backend-api/conversation/${encodeURIComponent(c.id)}`,{timeout:7000});}
  function openQuick(){document.getElementById('ng8-quick')?.remove();const modal=document.createElement('div');modal.id='ng8-quick';modal.innerHTML=`<div><input autofocus placeholder="Quick Open — Projects & conversations"><section></section><footer>${state.projects.length} Projects · ${state.chats.length} chats · Alt+K · ↑↓ · Entrée · Échap</footer></div>`;document.body.appendChild(modal);const input=modal.querySelector('input'),list=modal.querySelector('section');let items=[],sel=0;const paint=()=>{const q=norm(input.value),ps=sortedProjects().filter(p=>!q||norm(p.name).includes(q)).map(p=>({type:'PROJECT',title:p.name,sub:`${state.counts.get(p.id)??'?'} chats`,color:p.color,href:p.href})),cs=state.chats.filter(c=>{const p=state.projectById.get(c.projectId);return!q||norm(`${c.title} ${c.snippet} ${p?.name||''}`).includes(q);}).sort((a,b)=>b.updated-a.updated).slice(0,q?120:80).map(c=>{const p=state.projectById.get(c.projectId);return{type:'CHAT',title:c.title,sub:p?.name||'Hors projet',color:p?.color||'#607080',href:chatHref(c),chat:c};});items=[...ps,...cs].slice(0,140);sel=Math.min(sel,Math.max(0,items.length-1));list.innerHTML=items.map((x,i)=>`<button class="${i===sel?'sel':''}" data-i="${i}"><i style="--ng-project:${x.color}"></i><span>${esc(x.title)}</span><small>${esc(x.sub)}</small><em>${x.type}</em></button>`).join('');list.querySelectorAll('button').forEach(b=>{const x=items[Number(b.dataset.i)];b.onmouseenter=()=>x.chat&&prefetch(x.chat);b.onclick=()=>routeTo(x.href);});};input.oninput=()=>{sel=0;paint();};input.onkeydown=e=>{if(e.key==='ArrowDown'){e.preventDefault();sel=Math.min(sel+1,items.length-1);paint();}else if(e.key==='ArrowUp'){e.preventDefault();sel=Math.max(0,sel-1);paint();}else if(e.key==='Enter'&&items[sel]){e.preventDefault();routeTo(items[sel].href);}else if(e.key==='Escape')modal.remove();};modal.onmousedown=e=>{if(e.target===modal)modal.remove();};paint();setTimeout(()=>input.focus(),0);setHealth('quick',`OK · ${state.projects.length+state.chats.length} entrées`);}

  function scan(light=false){if(!document.body)return;ensureShell();brand();ensureMatrix();ensureBots();markRunning();decorateTurns(light||state.generation);if(!state.generation){decorateSidebar();renderPins();ensureCoach();}else document.getElementById('ng8-coach')?.setAttribute('hidden','');renderStatus();applyProjectTheme();}
  function meaningful(records){return records.some(r=>{const el=r.target?.nodeType===1?r.target:r.target?.parentElement;if(el?.closest?.(OWN_SEL))return false;const nodes=[...(r.addedNodes||[]),...(r.removedNodes||[])];return!nodes.length||nodes.some(n=>!(n.nodeType===1&&n.closest?.(OWN_SEL)));});}
  function schedule(delay=140,light=false){clearTimeout(state.scanTimer);state.scanTimer=setTimeout(()=>scan(light),delay);}
  function bind(){if(state.observer)return;state.observer=new MutationObserver(records=>{if(!meaningful(records))return;markRunning();if(location.pathname!==state.lastPath){state.lastPath=location.pathname;schedule(50,false);clearTimeout(state.routeTimer);state.routeTimer=setTimeout(async()=>{if(!state.generation){await indexEverything({quiet:true});renderPins();decorateSidebar();}},1500);return;}schedule(state.generation?(state.heavy?1300:750):150,state.generation);});state.observer.observe(document.documentElement,{subtree:true,childList:true});document.addEventListener('input',e=>{if(e.target?.matches?.('#prompt-textarea,[data-testid="prompt-textarea"],textarea')||e.target?.isContentEditable){clearTimeout(state.coachTimer);state.coachTimer=setTimeout(ensureCoach,70);}},true);document.addEventListener('keydown',e=>{if(e.altKey&&e.key.toLowerCase()==='k'){e.preventDefault();openQuick();}},true);addEventListener('resize',()=>{state.matrixResize?.();schedule(120,state.generation);},{passive:true});setInterval(markRunning,700);setInterval(async()=>{if(!state.generation){await indexEverything({quiet:true});await repairOrganization({manual:false});}},8*60*1000);}
  async function bootData(){const ok=await indexEverything();if(ok){renderPins();decorateSidebar();await repairOrganization({manual:false});setTimeout(tryNativePins,800);}}
  function bootstrap(){const start=()=>{ensureShell();ensureMatrix();ensureBots();brand();bind();for(let i=0;i<6;i++)setTimeout(()=>scan(i<2),i*180);setTimeout(bootData,260);};if(document.body)start();else{const mo=new MutationObserver(()=>{if(document.body){mo.disconnect();start();}});mo.observe(document.documentElement,{subtree:true,childList:true});}}
  bootstrap();
})();
