import fs from 'node:fs';
const rep=(file,a,b)=>{const s=fs.readFileSync(file,'utf8');if(!s.includes(a))throw new Error(`marker missing ${file}: ${a.slice(0,120)}`);fs.writeFileSync(file,s.replace(a,b));};

rep('.github/workflows/current-finalization.yml',`      - name: Runtime syntax\n        run: |\n          for f in background-v100.js app-v090.js pin-folders-v096.js visual-stability-v101.js sidebar-projects-authority-v112.js home-layout-v112.js analysis-bridge-v112.js reclassify-deep-v112.js matrix-guardian-v112.js performance-guard-v112.js turn-headers-v112.js continuity-v112.js chat-state-authority-v113.js breadcrumb-v113.js chat-attention-v113.js native-actions-v113.js conversation-load-guard-v113.js sidebar-icons-v114.js sidebar-metadata-v118.js sidebar-ux-v119.js native-actions-controller-v119.js interruption-guard-v119.js sidebar-projects-v121.js; do`,`      - name: Runtime syntax\n        run: |\n          for f in background-v100.js app-v090.js pin-folders-v096.js visual-stability-v101.js sidebar-projects-authority-v112.js home-layout-v112.js analysis-bridge-v112.js reclassify-deep-v112.js matrix-guardian-v112.js performance-guard-v112.js turn-headers-v112.js continuity-v112.js chat-state-authority-v113.js breadcrumb-v113.js chat-attention-v113.js conversation-load-guard-v113.js sidebar-icons-v114.js sidebar-metadata-v118.js sidebar-ux-v119.js interruption-guard-v119.js sidebar-projects-v121.js sidebar-actions-v123.js; do`);

// Run the new cross-engine session contract next to the generic experience gate in all OS/browser families.
rep('.github/workflows/current-finalization.yml',`      - name: Human / DOM / errors / UX / remount / anti-churn\n        working-directory: visual-lab\n        env:\n          NIAKGPT_BROWSER: ${{ matrix.browser }}\n        run: node experience-gate-v116.mjs`,`      - name: Human / DOM / errors / UX / remount / anti-churn\n        working-directory: visual-lab\n        env:\n          NIAKGPT_BROWSER: ${{ matrix.browser }}\n        run: node experience-gate-v116.mjs\n      - name: FULL LEFT SIDEBAR session UX — scroll / toggles / menus / remounts\n        working-directory: visual-lab\n        env:\n          NIAKGPT_BROWSER: ${{ matrix.browser }}\n        run: node sidebar-session-ux-v123.mjs`);
// The same snippet occurs in the second cross-platform family.
rep('.github/workflows/current-finalization.yml',`      - name: Human / DOM / errors / UX / remount / anti-churn\n        working-directory: visual-lab\n        env:\n          NIAKGPT_BROWSER: ${{ matrix.browser }}\n        run: node experience-gate-v116.mjs`,`      - name: Human / DOM / errors / UX / remount / anti-churn\n        working-directory: visual-lab\n        env:\n          NIAKGPT_BROWSER: ${{ matrix.browser }}\n        run: node experience-gate-v116.mjs\n      - name: FULL LEFT SIDEBAR session UX — scroll / toggles / menus / remounts\n        working-directory: visual-lab\n        env:\n          NIAKGPT_BROWSER: ${{ matrix.browser }}\n        run: node sidebar-session-ux-v123.mjs`);

rep('.github/workflows/current-finalization.yml',`      - name: Real extension runtime — left sidebar / hitboxes / menus / DOM / errors\n        working-directory: visual-lab\n        env:\n          NIAKGPT_BROWSER_LABEL: chromium\n          NIAKGPT_PROFILE: ${{ inputs.profile || 'runtime-cold-v116' }}\n        run: npx playwright test tests/sidebar-runtime-v116.spec.js --workers=1 --reporter=line`,`      - name: Real extension runtime — full human left-sidebar session\n        working-directory: visual-lab\n        env:\n          NIAKGPT_BROWSER_LABEL: chromium\n          NIAKGPT_PROFILE: ${{ inputs.profile || 'runtime-cold-v116' }}\n        run: npx playwright test tests/sidebar-human-ux-v123.spec.js --workers=1 --reporter=line`);
rep('.github/workflows/current-finalization.yml',`      - name: PRIMARY real Brave — left sidebar / pixel hitboxes / floating menus / UX`,`      - name: PRIMARY real Brave — FULL human sidebar / scroll / menus / recovery / long-work non-interference`);
rep('.github/workflows/current-finalization.yml',`          npx playwright test tests/sidebar-runtime-v116.spec.js --workers=1 --reporter=line 2>&1 | tee brave-runtime.log`,`          npx playwright test tests/sidebar-human-ux-v123.spec.js --workers=1 --reporter=line 2>&1 | tee brave-runtime.log`);
rep('.github/workflows/current-finalization.yml',`      - name: Native Project and chat actions\n        working-directory: visual-lab\n        env:\n          NIAKGPT_BROWSER: ${{ matrix.browser }}\n        run: node sidebar-native-actions-v113.mjs\n      - name: LEFT SIDEBAR pixel hitboxes + floating/nested menus\n        working-directory: visual-lab\n        env:\n          NIAKGPT_BROWSER: ${{ matrix.browser }}\n        run: node sidebar-hitboxes-v117.mjs`,`      - name: CURRENT LEFT SIDEBAR complete session contract\n        working-directory: visual-lab\n        env:\n          NIAKGPT_BROWSER: ${{ matrix.browser }}\n        run: node sidebar-session-ux-v123.mjs`);
rep('.github/workflows/current-finalization.yml',`        run: npx playwright test tests/runtime-current-v105.spec.js tests/multitab-failover-v097.spec.js tests/sidebar-runtime-v116.spec.js --workers=1 --reporter=line`,`        run: npx playwright test tests/runtime-current-v105.spec.js tests/multitab-failover-v097.spec.js tests/sidebar-human-ux-v123.spec.js --workers=1 --reporter=line`);
rep('.github/workflows/current-finalization.yml',`            visual-lab/artifacts/sidebar-hitboxes-v117/${{ matrix.browser }}\n            visual-lab/artifacts/experience-v116`,`            visual-lab/artifacts/sidebar-session-v123/${{ matrix.browser }}\n            visual-lab/artifacts/experience-v116`);

// Keep historical v116 runtime spec in the repo, but current suites no longer certify it.
rep('visual-lab/package.json',`playwright test --grep-invert \"native Sources/Outputs panels`,`playwright test --grep-invert \"real extension left-sidebar UX|native Sources/Outputs panels`);

rep('labs/static_validate_current.py',`experience=ROOT/'visual-lab/experience-gate-v116.mjs'; runtime_gate=ROOT/'visual-lab/tests/sidebar-runtime-v116.spec.js'; hitbox_gate=ROOT/'visual-lab/sidebar-hitboxes-v117.mjs';`,`experience=ROOT/'visual-lab/experience-gate-v116.mjs'; runtime_gate=ROOT/'visual-lab/tests/sidebar-human-ux-v123.spec.js'; session_ux_gate=ROOT/'visual-lab/sidebar-session-ux-v123.mjs'; hitbox_gate=ROOT/'visual-lab/sidebar-hitboxes-v117.mjs';`);
rep('labs/static_validate_current.py',`for path,label in ((experience,'cross-platform human DOM error UX gate'),(runtime_gate,'real extension runtime gate'),(hitbox_gate,'left-sidebar hitbox gate'),`,`for path,label in ((experience,'cross-platform human DOM error UX gate'),(runtime_gate,'real extension full-session human UX gate'),(session_ux_gate,'cross-engine full-session sidebar UX gate'),(hitbox_gate,'historical left-sidebar hitbox gate'),`);
rep('labs/static_validate_current.py',`for token in ('NIAKGPT_PROFILE','runtime-cold-v116','PROFILE.storageLocal','saved profile','Project row has two exclusive hitboxes','Chat actions menu is also a real top-layer overlay','atomic chat/action rows'):\n    if token not in runtime_text: fail('saved runtime/sidebar UX integration missing '+token)`,`for token in ('NIAKGPT_PROFILE','runtime-cold-v116','PROFILE.storageLocal','full human sidebar session UX','Projects catalog is complete, scrollable and visually stable','Project folder and chat drawer keep independent scroll positions','true toggles','Custom chat rename and move','Late sidebar mount and route diversity','Conversation limit CTA really starts continuity','Network/generation error recovery preserves draft','Long-work soak'):\n    if token not in runtime_text: fail('full-session runtime/sidebar UX integration missing '+token)\nsession_ux_text=session_ux_gate.read_text(encoding='utf-8')\nfor token in ('length:28','length:58','scroll snapped','Project menu is clipped/not hit-testable','sidebar remount did not recover','sidebar-session-ux-v123'):\n    if token not in session_ux_text: fail('cross-engine sidebar session coverage incomplete '+token)`);
rep('labs/static_validate_current.py',`for token in ('chromium, firefox, webkit','Human / DOM / errors / UX / remount / anti-churn','experience-gate-v116.mjs','sidebar-hitboxes-v117.mjs','LEFT SIDEBAR pixel hitboxes','PRIMARY real Brave — left sidebar'):` ,`for token in ('chromium, firefox, webkit','Human / DOM / errors / UX / remount / anti-churn','experience-gate-v116.mjs','sidebar-session-ux-v123.mjs','CURRENT LEFT SIDEBAR complete session contract','PRIMARY real Brave — FULL human sidebar'):`);
console.log('Applied current full-session human UX gates');
