import fs from 'node:fs';

const replace=(file,from,to)=>{
  const text=fs.readFileSync(file,'utf8');
  if(!text.includes(from))throw new Error(`Missing patch marker in ${file}: ${from.slice(0,120)}`);
  fs.writeFileSync(file,text.replace(from,to));
};
const replaceAll=(file,from,to)=>{
  const text=fs.readFileSync(file,'utf8');
  if(!text.includes(from))throw new Error(`Missing patch marker in ${file}: ${from.slice(0,120)}`);
  fs.writeFileSync(file,text.split(from).join(to));
};

// ---------------------------------------------------------------------------
// Version + single action owner
// ---------------------------------------------------------------------------
replace('manifest.json','"version": "0.9.69"','"version": "0.9.70"');
replace('manifest.json','        "native-actions-v113.css",','        "native-actions-v113.css",\n        "sidebar-actions-v123.css",');

replace('background-v100.js',"  'native-actions-controller-v119.js',\n  'native-actions-v113.js',","  'sidebar-actions-v123.js',");
replace('background-v100.js',"||item.includes(':native-actions-controller-v119.js:')||item.includes(':native-actions-v113.js:')","||item.includes(':sidebar-actions-v123.js:')");

// ---------------------------------------------------------------------------
// Legacy app: v121 is the only Projects renderer. app-v090 keeps all its other
// duties but must never destroy/recreate #ng8-pins once v121 is present.
// ---------------------------------------------------------------------------
replace('app-v090.js',`  function renderPins(){\n    const root=navRoot();if(!root)return;`,`  function renderPins(){\n    if(window.__NIAKGPT_SIDEBAR_PROJECTS_121__){\n      document.dispatchEvent(new CustomEvent('niakgpt:sidebar-projects-reconcile',{detail:{source:'app-v090'}}));\n      return;\n    }\n    const root=navRoot();if(!root)return;`);

// ---------------------------------------------------------------------------
// v121 catalog: stable order, scroll-preserving reconciliation, late/sidebar
// remount bootstrap. Chat timestamps must never reorder Project rows.
// ---------------------------------------------------------------------------
replace('sidebar-projects-v121.js',`  let observer=null,observedRoot=null,internal=false,timer=0,renderEpoch=0,lastPinFocus=null,lastPinFocusAt=0;`,`  let observer=null,observedRoot=null,internal=false,timer=0,renderEpoch=0,lastPinFocus=null,lastPinFocusAt=0,bootstrapObserver=null;\n  const sessionOrder=new Map();let sessionSeq=0;`);
replace('sidebar-projects-v121.js',`    const latest=id=>{let t=0;for(const c of cache.chats||[])if(normalizePid(c?.projectId)===id)t=Math.max(t,parseTime(c.updated||c.update_time||c.create_time));return t;};\n    return [...map.values()].sort((a,b)=>(core.has(b.id)?1:0)-(core.has(a.id)?1:0)||latest(b.id)-latest(a.id)||a.name.localeCompare(b.name,'fr'));`,`    const coreOrder=new Map((governance.coreProjectIds||[]).map((id,index)=>[normalizePid(id),index]));\n    for(const id of map.keys())if(!sessionOrder.has(id))sessionOrder.set(id,++sessionSeq);\n    return [...map.values()].sort((a,b)=>{\n      const ac=core.has(a.id),bc=core.has(b.id);if(ac!==bc)return ac?-1:1;\n      if(ac&&bc)return (coreOrder.get(a.id)??9999)-(coreOrder.get(b.id)??9999)||a.name.localeCompare(b.name,'fr');\n      return (sessionOrder.get(a.id)||0)-(sessionOrder.get(b.id)||0)||a.name.localeCompare(b.name,'fr');\n    });`);
replace('sidebar-projects-v121.js',`  function renderCatalog(box){\n    const projects=canonicalProjects(),wanted=new Set(projects.map(p=>p.id)),sig=catalogSignature(projects);let structural=false;`,`  function renderCatalog(box){\n    const projects=canonicalProjects(),wanted=new Set(projects.map(p=>p.id)),sig=catalogSignature(projects);let structural=false;\n    const listBefore=box.querySelector(':scope>.ng8-pin-list'),projectScroll=listBefore?.scrollTop||0;\n    const drawerScroll=new Map([...box.querySelectorAll('.ng96-pin-drawer')].map(d=>[normalizePid(d.dataset.pid),d.querySelector('.ng96-folder-list')?.scrollTop||0]));`);
replace('sidebar-projects-v121.js',`      box.dataset.ng121CatalogSig=sig;box.dataset.ng121CatalogCount=String(projects.length);box.dataset.ng121IdentityStable='1';`,`      box.dataset.ng121CatalogSig=sig;box.dataset.ng121CatalogCount=String(projects.length);box.dataset.ng121IdentityStable='1';\n      if(list.scrollTop!==projectScroll)list.scrollTop=projectScroll;\n      for(const d of box.querySelectorAll('.ng96-pin-drawer')){const sc=d.querySelector('.ng96-folder-list'),old=drawerScroll.get(normalizePid(d.dataset.pid));if(sc&&Number.isFinite(old)&&sc.scrollTop!==old)sc.scrollTop=old;}`);
replace('sidebar-projects-v121.js',`  function bind(){\n    const root=navRoot();if(!root||root===observedRoot&&observer)return;`,`  function bind(){\n    const root=navRoot();if(!root){armBootstrap();return;}if(root===observedRoot&&observer)return;`);
replace('sidebar-projects-v121.js',`    if(root.parentElement)observer.observe(root.parentElement,{childList:true,subtree:false});\n  }\n  async function load(){`,`    if(root.parentElement)observer.observe(root.parentElement,{childList:true,subtree:false});\n    bootstrapObserver?.disconnect();bootstrapObserver=null;\n  }\n  function armBootstrap(){\n    if(bootstrapObserver)return;bootstrapObserver=new MutationObserver(()=>{if(navRoot()){bootstrapObserver?.disconnect();bootstrapObserver=null;reconcile();}});\n    bootstrapObserver.observe(document.documentElement,{childList:true,subtree:true});\n    setTimeout(()=>{bootstrapObserver?.disconnect();bootstrapObserver=null;if(!navRoot())window.__NIAKGPT_DIAGNOSTICS__?.set('pins-ui','ATTENTE · sidebar ChatGPT non montée');},30000);\n  }\n  async function load(){`);
replace('sidebar-projects-v121.js',`  document.addEventListener('niakgpt:server-projects-ready',()=>schedule(0));document.addEventListener('niakgpt:server-indexed',()=>schedule(0));document.addEventListener('niakgpt:recovery-complete',()=>schedule(0));`,`  document.addEventListener('niakgpt:server-projects-ready',()=>schedule(0));document.addEventListener('niakgpt:server-indexed',()=>schedule(0));document.addEventListener('niakgpt:recovery-complete',()=>schedule(0));document.addEventListener('niakgpt:sidebar-projects-reconcile',()=>schedule(0));`);
replace('sidebar-projects-v121.js',`  window.addEventListener('pageshow',()=>{bind();schedule(0);});window.addEventListener('pagehide',()=>{observer?.disconnect();clearTimeout(timer);},{once:true});`,`  window.addEventListener('pageshow',()=>{bind();schedule(0);});window.addEventListener('pagehide',()=>{observer?.disconnect();bootstrapObserver?.disconnect();clearTimeout(timer);},{once:true});`);

// ---------------------------------------------------------------------------
// Project folders: cache updates may change dates without replacing the drawer.
// Merge direct/global project chats, preserve both scroll owners, and support a
// bounded explicit refresh from our Project action menu.
// ---------------------------------------------------------------------------
replace('pin-folders-v096.js',`  function projectSnapshotSignature(raw,pid){\n    if(!pid)return'';const chats=(raw?.chats||[]).filter(c=>normalizePid(c?.projectId)===pid).map(c=>[c.id,c.updated||c.update_time||0,c.title||'']);return JSON.stringify([raw?.counts?.[pid]??null,chats]);\n  }`,`  function projectSnapshotSignature(raw,pid){\n    if(!pid)return'';const chats=(raw?.chats||[]).filter(c=>normalizePid(c?.projectId)===pid).map(c=>[c.id,c.title||'',normalizePid(c.projectId||pid)]).sort((a,b)=>String(a[0]).localeCompare(String(b[0])));return JSON.stringify([raw?.counts?.[pid]??null,chats]);\n  }`);
replace('pin-folders-v096.js',`    const source=direct.length?direct:(cache.chats||[]).filter(c=>normalizePid(c?.projectId)===pid);\n    const map=new Map();`,`    const source=[...(cache.chats||[]).filter(c=>normalizePid(c?.projectId)===pid),...direct];\n    const map=new Map();`);
replace('pin-folders-v096.js',`  function renderDrawer(pid,anchor){\n    pid=normalizePid(pid);closeDrawers();if(!pid||!anchor)return;`,`  function renderDrawer(pid,anchor){\n    pid=normalizePid(pid);const outer=document.querySelector('#ng8-pins>.ng8-pin-list'),outerScroll=outer?.scrollTop||0,previous=document.getElementById(drawerId(pid)),innerScroll=previous?.querySelector('.ng96-folder-list')?.scrollTop||0;closeDrawers();if(!pid||!anchor)return;`);
replace('pin-folders-v096.js',`    entry.insertAdjacentElement('afterend',drawer);drawerDirty=false;`,`    entry.insertAdjacentElement('afterend',drawer);drawerDirty=false;\n    if(outer&&outer.scrollTop!==outerScroll)outer.scrollTop=outerScroll;const restoredList=drawer.querySelector('.ng96-folder-list');if(restoredList&&innerScroll)restoredList.scrollTop=Math.min(innerScroll,Math.max(0,restoredList.scrollHeight-restoredList.clientHeight));`);
replace('pin-folders-v096.js',`  document.addEventListener('niakgpt:pins-rendered',()=>{bindBox();rehydrate();});`,`  document.addEventListener('niakgpt:pins-rendered',()=>{bindBox();rehydrate();});\n  document.addEventListener('niakgpt:hydrate-project',event=>{const pid=normalizePid(event.detail?.projectId||'');if(!pid)return;loadState.delete(pid);if(openPid===pid){drawerDirty=true;schedule(0);}hydrateProject(pid);});`);

// ---------------------------------------------------------------------------
// Interruption recovery: the limit CTA must actually continue, and network/error
// detection must cover modern native generation/fetch failures without scanning
// normal assistant prose.
// ---------------------------------------------------------------------------
replace('interruption-guard-v119.js',`  const NETWORK_RX=/(connexion\\s+(?:perdue|interrompue)|connection\\s+(?:lost|interrupted)|network\\s+error|erreur\\s+réseau|disconnected|déconnecté|websocket.{0,24}(?:error|closed|failed)|reconnecting|reconnexion\\s+en\\s+cours)/i;`,`  const NETWORK_RX=/(connexion\\s+(?:perdue|interrompue)|connection\\s+(?:lost|interrupted)|network\\s+error|erreur\\s+réseau|disconnected|déconnecté|websocket.{0,24}(?:error|closed|failed)|reconnecting|reconnexion\\s+en\\s+cours|failed\\s+to\\s+fetch|fetch\\s+failed|something\\s+went\\s+wrong|there\\s+was\\s+an\\s+error\\s+(?:generating|processing)|une\\s+erreur\\s+est\\s+survenue|erreur\\s+lors\\s+de\\s+la\\s+(?:génération|generation)|impossible\\s+de\\s+générer|unable\\s+to\\s+generate)/i;`);
replace('interruption-guard-v119.js',`  document.addEventListener('click',event=>{\n    const b=event.target instanceof Element?event.target.closest('#ng119-interruption .ng100-continue'):null;if(!b)return;\n    setTimeout(()=>clearBar(),0);\n  },false);`,`  document.addEventListener('click',event=>{\n    const b=event.target instanceof Element?event.target.closest('#ng119-interruption .ng100-continue'):null;if(!b)return;\n    event.preventDefault();const chatId=incident?.chatId||String(location.pathname).match(/\\/c\\/([A-Za-z0-9_-]+)/)?.[1]||'';\n    if(chatId)window.__NIAKGPT_CONTINUITY__?.continueFrom?.(chatId);setTimeout(()=>clearBar(),0);\n  },false);`);

// ---------------------------------------------------------------------------
// Packaging + static contracts
// ---------------------------------------------------------------------------
replace('tools/package-extension.mjs',`  'sidebar-ux-v119.js','sidebar-ux-v119.css','native-actions-controller-v119.js','interruption-guard-v119.js','interruption-guard-v119.css',`,`  'sidebar-ux-v119.js','sidebar-ux-v119.css','sidebar-actions-v123.js','sidebar-actions-v123.css','interruption-guard-v119.js','interruption-guard-v119.css',`);
replace('tools/package-extension.mjs',`  'chat-state-authority-v113.js','breadcrumb-v113.js','chat-attention-v113.js','chat-attention-v113.css','native-actions-v113.js','native-actions-v113.css','conversation-load-guard-v113.js',`,`  'chat-state-authority-v113.js','breadcrumb-v113.js','chat-attention-v113.js','chat-attention-v113.css','native-actions-v113.css','conversation-load-guard-v113.js',`);
replace('tools/package-extension.mjs',`  'sidebar-projects-authority-v109.js','sidebar-projects-authority-v110.js','sidebar-projects-authority-v111.js','native-rename-v112.js','native-rename-v112.css','breadcrumb-v100.js'`,`  'sidebar-projects-authority-v109.js','sidebar-projects-authority-v110.js','sidebar-projects-authority-v111.js','native-rename-v112.js','native-rename-v112.css','native-actions-controller-v119.js','native-actions-v113.js','breadcrumb-v100.js'`);

// Static validator: move production contract from native menu cloning to one custom owner.
replace('labs/static_validate_current.py',"if manifest.get('version')!='0.9.69': fail(f\"version={manifest.get('version')}\")","if manifest.get('version')!='0.9.70': fail(f\"version={manifest.get('version')}\")");
replace('labs/static_validate_current.py',`'native-actions-v113.js','conversation-load-guard-v113.js','sidebar-icons-v114.js','sidebar-ux-v119.js','pin-folders-v096.js','native-actions-controller-v119.js','interruption-guard-v119.js'`,`'conversation-load-guard-v113.js','sidebar-icons-v114.js','sidebar-ux-v119.js','pin-folders-v096.js','sidebar-actions-v123.js','interruption-guard-v119.js'`);
replace('labs/static_validate_current.py',`    if isolated.index('native-actions-controller-v119.js')>=isolated.index('native-actions-v113.js'): fail('native-only action controller must register before v113 production click handler')\n`,`    if 'native-actions-controller-v119.js' in isolated or 'native-actions-v113.js' in isolated: fail('legacy dual native action owners are still wired')\n    if isolated.index('sidebar-actions-v123.js')<=isolated.index('pin-folders-v096.js'): fail('custom action owner must load after folder rows exist')\n`);
replace('labs/static_validate_current.py',`for required_css in ('sidebar-metadata-v118.css','sidebar-projects-authority-v112.css','home-layout-v112.css','matrix-guardian-v112.css','performance-guard-v112.css','native-da-v112.css','sidebar-icons-v114.css','native-actions-v113.css','chat-attention-v113.css','sidebar-ux-v119.css','interruption-guard-v119.css'):` ,`for required_css in ('sidebar-metadata-v118.css','sidebar-projects-authority-v112.css','home-layout-v112.css','matrix-guardian-v112.css','performance-guard-v112.css','native-da-v112.css','sidebar-icons-v114.css','native-actions-v113.css','sidebar-actions-v123.css','chat-attention-v113.css','sidebar-ux-v119.css','interruption-guard-v119.css'):`);
const start=`actions=(ROOT/'native-actions-v113.js').read_text(encoding='utf-8')\nif 'invokeNativeMenu' not in actions or 'fallbackMove' not in actions: fail('v113 tested action primitives missing')\nif 'data-ng112-native-projects' not in actions: fail('native actions do not stage passive Projects marks')\nfor token in ('placeFloatingMenu','ng113-native-menu-floating','ensureChatEntry','ng96-chat-entry','showPopover','ng113TopLayer','menuBaseline','menuSession','sessionVisibleMenus','resetFloatingMenu','fallbackOutsideHandler','actionEpoch','actionOpening','actionCurrent','claimTriggerMenu','menuStrict','aria-busy',\"b.getAttribute('aria-haspopup')==='menu'\",'source.isConnected'):\n    if token not in actions: fail('left-sidebar action lifecycle/session/race cleanup missing '+token)\nif 'buttons.at(-1)' in actions: fail('native action can click arbitrary last native button')\ncontroller=(ROOT/'native-actions-controller-v119.js').read_text(encoding='utf-8')\nfor token in ('normalizePid','resolveNativeProjectRow','showMoreButton','closeSession','session?.key===key','opening?.key===key','aucun fallback custom','currentConversationMenuButton','stopImmediatePropagation','ng119Owned'):\n    if token not in controller: fail('native-only reliable actions controller incomplete '+token)\nif 'fallbackChatMenu(' in controller or 'fallbackMove(' in controller: fail('v119 production controller reintroduced custom chat action fallback')\n`;
const next=`actions=(ROOT/'sidebar-actions-v123.js').read_text(encoding='utf-8')\nfor token in ('ng123-action-menu','ng123-rename-dialog','data-ng123-action','openMenu','state?.button===button','renameChat','moveChat','nativeProjectRename','exactProjectRow','/project','Hors projet','niakgpt:hydrate-project','stopImmediatePropagation'):\n    if token not in actions: fail('single-owner custom sidebar action lifecycle incomplete '+token)\nfor forbidden in ('native-actions-controller-v119.js','native-actions-v113.js'):\n    if forbidden in isolated: fail('legacy action owner wired '+forbidden)\n`;
replace('labs/static_validate_current.py',start,next);
replace('labs/static_validate_current.py',`for token in ('window.__NIAKGPT_SIDEBAR_UX_119__=true','canonicalProjects','renderCatalog','catalogue complet','ng121PinsReady','ng121PlacementReady','nativeProjectSection','primaryTail','data-ng121-catalog','projects.map(row).join','MutationObserver'):` ,`for token in ('window.__NIAKGPT_SIDEBAR_UX_119__=true','canonicalProjects','renderCatalog','catalogue complet','ng121PinsReady','ng121PlacementReady','nativeProjectSection','primaryTail','data-ng121-catalog','projects.map(row).join','MutationObserver','sessionOrder','armBootstrap','projectScroll','drawerScroll','niakgpt:sidebar-projects-reconcile'):`);
replace('labs/static_validate_current.py',`for token in ('drawerDirty','cooperativeNode','existing.previousElementSibling===entry','ng96-chat-entry','hydrateProject','publishProjectChats','bridgeBusy','niakgpt:activity-changed','Chargement des conversations'):` ,`for token in ('drawerDirty','cooperativeNode','existing.previousElementSibling===entry','ng96-chat-entry','hydrateProject','publishProjectChats','bridgeBusy','niakgpt:activity-changed','Chargement des conversations','innerScroll','outerScroll','niakgpt:hydrate-project'):`);
replace('labs/static_validate_current.py',`for token in ('LIMIT_RX','VERIFY_RX','NETWORK_RX','nativeRetry','markCurrentOut','ng100-continue','tryNativeRecovery','incident.retried','resumePrompt'):` ,`for token in ('LIMIT_RX','VERIFY_RX','NETWORK_RX','nativeRetry','markCurrentOut','ng100-continue','tryNativeRecovery','incident.retried','resumePrompt','continueFrom?.(chatId)','failed\\s+to\\s+fetch'):`);

console.log('Applied NiakGPT 0.9.70 human UX migration');
