import fs from 'node:fs';
const rep=(file,a,b)=>{const s=fs.readFileSync(file,'utf8');if(!s.includes(a))throw new Error(`marker missing ${file}: ${a.slice(0,100)}`);fs.writeFileSync(file,s.replace(a,b));};

rep('sidebar-projects-v121.js',`  let observer=null,observedRoot=null,internal=false,timer=0,renderEpoch=0,lastPinFocus=null,lastPinFocusAt=0,bootstrapObserver=null;\n  const sessionOrder=new Map();let sessionSeq=0;`,`  let observer=null,observedRoot=null,internal=false,timer=0,renderEpoch=0,lastPinFocus=null,lastPinFocusAt=0,bootstrapObserver=null,projectScrollMemory=0;\n  const sessionOrder=new Map();let sessionSeq=0;`);
rep('sidebar-projects-v121.js',`    const listBefore=box.querySelector(':scope>.ng8-pin-list'),projectScroll=listBefore?.scrollTop||0;`,`    const listBefore=box.querySelector(':scope>.ng8-pin-list'),projectScroll=listBefore?listBefore.scrollTop:projectScrollMemory;`);
rep('sidebar-projects-v121.js',`      if(list.scrollTop!==projectScroll)list.scrollTop=projectScroll;`,`      if(list.scrollTop!==projectScroll)list.scrollTop=projectScroll;projectScrollMemory=list.scrollTop;`);
rep('sidebar-projects-v121.js',`  function reconcile(){clearTimeout(timer);timer=0;if(internal)return;const box=ensureBox();if(!box)return;renderCatalog(box);place(box);bind();hideWelcome();window.__NIAKGPT_DIAGNOSTICS__?.set('sidebar-ux-119',\`OK · Projects \${box.dataset.ng121Placement||'stable'} · autorité v121 unique\`);}`,`  function reconcile(){clearTimeout(timer);timer=0;if(internal)return;const box=ensureBox();if(!box){bind();return;}renderCatalog(box);place(box);bind();hideWelcome();window.__NIAKGPT_DIAGNOSTICS__?.set('sidebar-ux-119',\`OK · Projects \${box.dataset.ng121Placement||'stable'} · autorité v121 unique\`);}`);
rep('sidebar-projects-v121.js',`  document.addEventListener('focusin',event=>{`,`  document.addEventListener('scroll',event=>{const target=event.target instanceof Element?event.target:null;if(target?.matches?.('#ng8-pins>.ng8-pin-list'))projectScrollMemory=target.scrollTop;},true);\n  document.addEventListener('focusin',event=>{`);

rep('pin-folders-v096.js',`  const loadState=new Map();`,`  const loadState=new Map(),drawerScrollMemory=new Map();`);
rep('pin-folders-v096.js',`    pid=normalizePid(pid);const outer=document.querySelector('#ng8-pins>.ng8-pin-list'),outerScroll=outer?.scrollTop||0,previous=document.getElementById(drawerId(pid)),innerScroll=previous?.querySelector('.ng96-folder-list')?.scrollTop||0;closeDrawers();if(!pid||!anchor)return;`,`    pid=normalizePid(pid);const outer=document.querySelector('#ng8-pins>.ng8-pin-list'),outerScroll=outer?.scrollTop||0,previous=document.getElementById(drawerId(pid)),innerScroll=previous?.querySelector('.ng96-folder-list')?.scrollTop??drawerScrollMemory.get(pid)??0;if(previous){const old=previous.querySelector('.ng96-folder-list');if(old)drawerScrollMemory.set(pid,old.scrollTop);}closeDrawers();if(!pid||!anchor)return;`);
rep('pin-folders-v096.js',`    if(outer&&outer.scrollTop!==outerScroll)outer.scrollTop=outerScroll;const restoredList=drawer.querySelector('.ng96-folder-list');if(restoredList&&innerScroll)restoredList.scrollTop=Math.min(innerScroll,Math.max(0,restoredList.scrollHeight-restoredList.clientHeight));`,`    if(outer&&outer.scrollTop!==outerScroll)outer.scrollTop=outerScroll;const restoredList=drawer.querySelector('.ng96-folder-list');if(restoredList&&innerScroll){restoredList.scrollTop=Math.min(innerScroll,Math.max(0,restoredList.scrollHeight-restoredList.clientHeight));drawerScrollMemory.set(pid,restoredList.scrollTop);}`);
rep('pin-folders-v096.js',`  document.addEventListener('niakgpt:pins-rendered',()=>{bindBox();rehydrate();});`,`  document.addEventListener('scroll',event=>{const list=event.target instanceof Element?event.target.closest?.('#ng8-pins .ng96-folder-list'):null;if(!list)return;const drawer=list.closest('.ng96-pin-drawer'),pid=normalizePid(drawer?.dataset.pid||'');if(pid)drawerScrollMemory.set(pid,list.scrollTop);},true);\n  document.addEventListener('niakgpt:pins-rendered',()=>{bindBox();rehydrate();});`);

rep('sidebar-actions-v123.js',`    await updateCache(raw=>{const chats=(raw?.chats||[]).map(c=>c?.id===id?{...c,projectId:target}:c),projectChats={};for(const [p,list] of Object.entries(raw?.projectChats||{}))projectChats[p]=(list||[]).filter(c=>c?.id!==id);const moved=chats.find(c=>c?.id===id);if(target&&moved)(projectChats[target]??=[]).unshift({...moved,projectId:target});return{...raw,at:Date.now(),chats,projectChats};});`,`    await updateCache(raw=>{const before=(raw?.chats||[]).find(c=>c?.id===id),from=normalizePid(before?.projectId||''),chats=(raw?.chats||[]).map(c=>c?.id===id?{...c,projectId:target}:c),projectChats={};for(const [p,list] of Object.entries(raw?.projectChats||{}))projectChats[p]=(list||[]).filter(c=>c?.id!==id);const moved=chats.find(c=>c?.id===id);if(target&&moved)(projectChats[target]??=[]).unshift({...moved,projectId:target});const counts={...(raw?.counts||{})};if(from&&from!==target&&Number.isFinite(Number(counts[from])))counts[from]=Math.max(0,Number(counts[from])-1);if(target&&from!==target&&Number.isFinite(Number(counts[target])))counts[target]=Number(counts[target])+1;return{...raw,at:Date.now(),chats,projectChats,counts};});`);

rep('labs/static_validate_current.py',`'sessionOrder','armBootstrap','projectScroll','drawerScroll','niakgpt:sidebar-projects-reconcile'`,`'sessionOrder','armBootstrap','projectScroll','drawerScroll','projectScrollMemory','niakgpt:sidebar-projects-reconcile'`);
rep('labs/static_validate_current.py',`'innerScroll','outerScroll','niakgpt:hydrate-project'`,`'innerScroll','outerScroll','drawerScrollMemory','niakgpt:hydrate-project'`);
console.log('Applied 0.9.70 remount/scroll hardening');
